"""auto migration

Revision ID: 00fd0c887f45
Revises:
Create Date: 2025-12-09 03:32:42.473235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00fd0c887f45"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before altering (for fresh database initialization)
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # Only alter function_call table if it exists
    if "function_call" in existing_tables:
        with op.batch_alter_table("function_call", schema=None) as batch_op:
            # Check if columns exist before altering
            columns = [col["name"] for col in inspector.get_columns("function_call")]
            if "status" in columns:
                batch_op.alter_column(
                    "status",
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum("RUNNING", "SUCCEEDED", "FAILED", name="functioncallstatus"),
                    existing_nullable=False,
                )
            if "trigger_type" in columns:
                batch_op.alter_column(
                    "trigger_type",
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum("MANUAL", "SCHEDULE", name="triggertype"),
                    existing_nullable=False,
                )

    # Only alter function_schedule table if it exists
    if "function_schedule" in existing_tables:
        with op.batch_alter_table("function_schedule", schema=None) as batch_op:
            # Check if column already exists before adding
            columns = [col["name"] for col in inspector.get_columns("function_schedule")]
            if "input_data" not in columns:
                batch_op.add_column(sa.Column("input_data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before altering
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # Only alter function_schedule table if it exists
    if "function_schedule" in existing_tables:
        with op.batch_alter_table("function_schedule", schema=None) as batch_op:
            # Check if column exists before dropping
            columns = [col["name"] for col in inspector.get_columns("function_schedule")]
            if "input_data" in columns:
                batch_op.drop_column("input_data")

    # Only alter function_call table if it exists
    if "function_call" in existing_tables:
        with op.batch_alter_table("function_call", schema=None) as batch_op:
            # Check if columns exist before altering
            columns = [col["name"] for col in inspector.get_columns("function_call")]
            if "trigger_type" in columns:
                batch_op.alter_column(
                    "trigger_type",
                    existing_type=sa.Enum("MANUAL", "SCHEDULE", name="triggertype"),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=False,
                )
            if "status" in columns:
                batch_op.alter_column(
                    "status",
                    existing_type=sa.Enum(
                        "RUNNING", "SUCCEEDED", "FAILED", name="functioncallstatus"
                    ),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=False,
                )

    # ### end Alembic commands ###
