"""auto migration

Revision ID: 00fd0c887f45
Revises: 
Create Date: 2025-12-09 03:32:42.473235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00fd0c887f45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function_call', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='functioncallstatus'),
               existing_nullable=False)
        batch_op.alter_column('trigger_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MANUAL', 'SCHEDULE', name='triggertype'),
               existing_nullable=False)

    with op.batch_alter_table('function_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function_schedule', schema=None) as batch_op:
        batch_op.drop_column('input_data')

    with op.batch_alter_table('function_call', schema=None) as batch_op:
        batch_op.alter_column('trigger_type',
               existing_type=sa.Enum('MANUAL', 'SCHEDULE', name='triggertype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', name='functioncallstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###

