"""add_extension_table

Revision ID: 08af93f2c4ed
Revises: 00fd0c887f45
Create Date: 2025-12-09 04:14:37.827321

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08af93f2c4ed"
down_revision: Union[str, None] = "00fd0c887f45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # Create extension table if it doesn't exist
    if "extension" not in existing_tables:
        op.create_table(
            "extension",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
            sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
            sa.Column("author", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
            sa.Column("repo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
            sa.Column("install_path", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
            sa.Column("entry_point", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
            sa.Column("is_enabled", sa.Boolean(), nullable=False),
            sa.Column("installed_at", sa.DateTime(), nullable=False),
            sa.Column("installed_by_user_id", sa.Uuid(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["installed_by_user_id"],
                ["user.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        with op.batch_alter_table("extension", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_extension_name"), ["name"], unique=True)
    else:
        # Table exists, just ensure index exists
        with op.batch_alter_table("extension", schema=None) as batch_op:
            indexes = [idx["name"] for idx in inspector.get_indexes("extension")]
            if "ix_extension_name" not in indexes:
                batch_op.create_index(batch_op.f("ix_extension_name"), ["name"], unique=True)

    # Drop temporary table if it exists (leftover from previous migration attempts)
    if "_alembic_tmp_function_call" in existing_tables:
        op.drop_table("_alembic_tmp_function_call")

    # Only alter function_call table if it exists
    if "function_call" in existing_tables:
        columns = [col["name"] for col in inspector.get_columns("function_call")]
        with op.batch_alter_table("function_call", schema=None) as batch_op:
            if "status" in columns:
                batch_op.alter_column(
                    "status",
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum("RUNNING", "SUCCEEDED", "FAILED", name="functioncallstatus"),
                    existing_nullable=False,
                )
            if "trigger_type" in columns:
                batch_op.alter_column(
                    "trigger_type",
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.Enum("MANUAL", "SCHEDULE", name="triggertype"),
                    existing_nullable=False,
                )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # Only alter function_call table if it exists
    if "function_call" in existing_tables:
        columns = [col["name"] for col in inspector.get_columns("function_call")]
        with op.batch_alter_table("function_call", schema=None) as batch_op:
            if "trigger_type" in columns:
                batch_op.alter_column(
                    "trigger_type",
                    existing_type=sa.Enum("MANUAL", "SCHEDULE", name="triggertype"),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=False,
                )
            if "status" in columns:
                batch_op.alter_column(
                    "status",
                    existing_type=sa.Enum(
                        "RUNNING", "SUCCEEDED", "FAILED", name="functioncallstatus"
                    ),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=False,
                )

    # Drop extension table if it exists
    if "extension" in existing_tables:
        with op.batch_alter_table("extension", schema=None) as batch_op:
            indexes = [idx["name"] for idx in inspector.get_indexes("extension")]
            if "ix_extension_name" in indexes:
                batch_op.drop_index(batch_op.f("ix_extension_name"))
        op.drop_table("extension")

    # ### end Alembic commands ###
