"""add scheduler configuration settings

Revision ID: 5b77edb363ab
Revises: f5e9c31fec5f
Create Date: 2025-12-09 16:42:41.322686

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5b77edb363ab"
down_revision: Union[str, None] = "f5e9c31fec5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
