"""add_token_scope_and_function_metrics

Revision ID: ff0030cada65
Revises: h8i9j0k1l2m3
Create Date: 2026-01-19 19:47:48.205540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff0030cada65'
down_revision: Union[str, None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('function_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_peak_mb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cpu_time_ms', sa.Integer(), nullable=True))

    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.alter_column('auth_portal_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('auth_portal_background_color')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_portal_background_color', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('auth_portal_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('function_call', schema=None) as batch_op:
        batch_op.drop_column('cpu_time_ms')
        batch_op.drop_column('memory_peak_mb')

    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('scope')

    # ### end Alembic commands ###

