"""auto migration

Revision ID: f5e9c31fec5f
Revises: 08af93f2c4ed
Create Date: 2025-12-09 04:20:48.762180

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f5e9c31fec5f"
down_revision: Union[str, None] = "08af93f2c4ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
